### ISSUE TITLE
Disabling a user fails with Spring Boot newer than 1.4.0

### ISSUE THREAD

**Issue by dschadow** [jtmelton/appsensor#74] opened 2017-03-19 15:18 UTC
The demo-appsensor-local project fails to disable a malicious user as configured. The log contains the following entry:

WARN  o.o.a.l.r.LocalResponseHandler - Response executed for user <user>, Action: Disabling malicious account, delegating to configured user manager <org.owasp.appsensor.integration.springsecurity.response.SpringSecurityUserManager>
INFO  o.o.a.i.s.r.SpringSecurityUserManager - Request received to disable user <user>.
WARN  o.o.a.i.s.r.SpringSecurityUserManager - Could not disable user [user] since the spring security UserDetailsManager is not properly configured.

Logging the user out as the first step works fine, disabling him doesn't. The sample is working with the given Spring Boot version but fails starting with Spring Boot 1.4.1 (1.4.0 is working) with the same error message.

**Comment by jtmelton** [comment] 2017-03-20 02:43
@dschadow so to be clear - this works as is in the current boot version in the repository (1.2.3) all the way up to 1.4.0, but if I bump the version of the demo project to 1.4.1 it should stop working?

**Comment by dschadow** [comment] 2017-03-20 06:01
@jtmelton exactly.

**Comment by jtmelton** [comment] 2017-03-20 06:43
@rwinch any thoughts on why this might be the case? Looks like this section might be the offending one: https://github.com/jtmelton/appsensor/blob/master/integrations/appsensor-integration-spring-security/src/main/java/org/owasp/appsensor/integration/springsecurity/response/SpringSecurityUserManager.java#L67 . I'm not doing anything complex here, but it looks like there was some change in spring boot 1.4.0 to 1.4.1. That same change looks to be coupled to a change from 4.1.1 to 4.1.3 in spring security. Is there any quick answers to this that you know of?

**Comment by dschadow** [comment] 2017-03-20 06:51
Not yet. I was investigating the problem a little bit and started testing different Spring Boot versions. The only thing I've figured out was the null object causing the exception. I'll continue my research.

**Comment by jtmelton** [comment] 2017-03-20 06:52
@dschadow I was actually asking Rob (spring security lead) this question to see if he could give any insight without us having to spend a bunch of time debugging.

**Comment by dschadow** [comment] 2017-03-20 06:54
😀uh haven't noticed that...

**Comment by rwinch** [comment] 2017-03-20 14:18
@jtmelton Nothing comes to mind why this would happen. Do you have a way for me to easily reproduce the issue?

**Comment by jtmelton** [comment] 2017-03-20 16:18
@rwinch not really - I'll poke around, but figured it was worth asking to see if there was an obvious answer. I may bug you again, but I'll work through it - thanks!

**Comment by rwinch** [comment] 2017-03-24 21:38
@jtmelton Thanks for the response. Don't hesitate to reach out if you can use some help and have a way to reproduce it :)

**Comment by jtmelton** [comment] 2017-03-25 03:09
@dschadow I actually can't reproduce this at all on 1.4.x (spring boot). 1.5.x fails with some compilation errors (classes/packages removed), but 1.4.0-1.4.5 all worked fine. I got the same behavior as 1.2.3.

**Comment by dschadow** [comment] 2017-03-27 10:18
@jtmelton I can reproduce this issue on OS X 10.12.3 with Java 1.8.0_121. With one minor correction: After some more testing I am able to reproduce it with Spring Boot 1.4.0. Spring Boot 1.3.8 is working, so the problem starts with Spring Boot 1.4.0. 

What I do is that I log into the sample application and start submitting script tags. With all tested Spring Boot versions I'm logged out after some attacks (everything working here). After that I log in again and submit some new script tags. With 1.3.8 (or older) the user is disabled after the next number of attacks. With Spring Boot 1.4.0 and newer I do receive the following log message:

WARN  o.o.a.i.s.r.SpringSecurityUserManager - Could not disable user [user] since the spring security UserDetailsManager is not properly configured.

The user is not disabled. I do have the same behavior in my own test application https://github.com/dschadow/ApplicationIntrusionDetection So there seems to be a problem with disabling users in newer Spring Security versions. 

I've tested the sample application with AppSensor 2.1 as in the repo and with the latest 2.3.1. The only thing I've deleted is the test since that is not working with newer Spring Boot versions. Haven't tested Spring Boot 1.5.x with the sample application because of the required changes. I can reproduce the disabling user problem in my sample application based on the latest Spring Boot so I guess the sample app won't work as well.

**Comment by jtmelton** [comment] 2017-03-27 15:19
@dschadow ahh, I failed to read this properly. I only got to testing logout, not disable. I'll re-test tonight/tomorrow and see if I can figure it out. Thanks!

**Comment by jtmelton** [comment] 2017-03-30 03:47
@dschadow ok, I've at least been able to replicate this now - I'm working through it and will let you know what I find.

**Comment by jtmelton** [comment] 2017-03-30 05:47
@dschadow I think I've got a fix locally that should resolve this. I'm going to do a bit more testing, and then will make the change. It boils down to a bug in my original code. It appears the code probably shouldn't have worked in the first place, but the configuration has been updated in the latest versions of boot to be more accurate, which exposed the original bug. I'll update this ticket when the change is pushed. Thanks for finding this and working through it with me!

**Comment by dschadow** [comment] 2017-04-01 11:15
Thanks for fixing it. Feel free to ping me to test.

**Comment by jtmelton** [comment] 2017-04-02 03:32
@dschadow great, thanks. I just pushed a snapshot release for testing. Would you mind trying to change the version of the appsensor spring security integration from 2.1.0  to 2.3.2-SNAPSHOT ( https://github.com/jtmelton/appsensor/blob/master/sample-apps/demo-appsensor-local/pom.xml#L99 ) ? You might have to add the snapshot repo ( see https://github.com/jtmelton/appsensor/blob/master/pom.xml#L30 ). If that's successful for you, I'll push 2.3.2.

**Comment by dschadow** [comment] 2017-04-02 07:14
@jtmelton Tested with my demo application, works perfect. Thanks!

**Comment by jtmelton** [comment] 2017-04-05 05:56
@dschadow ok, thanks for testing. I pushed 2.3.2 to central - should show up shortly. Closing the issue now. Appreciate your help working through it.

**Closed by jtmelton** 2017-04-05 05:56 UTC
